### ISSUE TITLE
Fix for SCSS debug info

### ISSUE THREAD

**Issue by qianc** [scottjehl/Respond#148]
When including debug info in files created with Compass/SCSS, Respond.js won't work. An easy fix is to add "(?![\s]*-)" to the regex on line 109.

Before:

``` javascript
var qs = styles.match(  /@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi )
```

After:

``` javascript
var qs = styles.match(  /@media(?![\s]*-)[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi ),
```

The skips media queries of the following type:

``` css
@media -sass-debug-info{filename{font-family:<filename>}line{font-family:<line>}}
```
