### ISSUE TITLE
Having lots of separate media queries will eventually fail

### ISSUE THREAD

**Issue by TheDutchCoder** [scottjehl/Respond#247]
I'm working on a really large website at the moment, where I use media queries for every single object, instead of having one media query per "device" and putting all the rules in there.

This will eventually break the script as in: it won't apply all the right styles anymore. I'm not sure what the actual limit is, but my CSS file is 6200+ lines and I have about 52 media queries (all of them "min-width: 40em" or "min-width: 60em").

To give an example of how I use media queries:

``` css
.some-object {
  margin: 1em 0;
}

@media only screen and (min-width: 40em) {

  .some-object {
    margin: 2em 0;
  }

}

@media only screen and (min-width: 60em) {

  .some-object {
    margin: 3em 0;
  }

}

.some-other-object {
  color: red;
}

@media only screen and (min-width: 40em) {

  .some-other-object {
    color: orange;
  }

}

@media only screen and (min-width: 60em) {

  .some-other-object {
    color: green;
  }

}
```

This happens on a per-object basis, instead of a more traditional:

``` css
.some-object {
  margin: 1em 0;
}

.some-other-object {
  color: red;
}

@media only screen and (min-width: 40em) {

  .some-object {
    margin: 2em 0;
  }

  .some-other-object {
    color: orange;
  }

}

@media only screen and (min-width: 60em) {

  .some-object {
    margin: 3em 0;
  }

  .some-other-object {
    color: green;
  }

}
```

Any insights would be appreciated, as it's a pain to maintain objects in three different places.
