### ISSUE TITLE
view-mode: minimized

### ISSUE THREAD

**Issue by vxsx** [scottjehl/Respond#81]
I use something like this for [Opera's speed dial](http://dev.opera.com/articles/view/opera-speed-dial-enhancements/):

``` css
@media screen and (view-mode: minimized) {
     body { background: url(/img/logo.jpg) no-repeat center center; }
     body * { display: none }
}
```

It's all good and nice, but it always applies in IE when I use respond.js. 
Any solution besides removing this media query from stylesheet?
